packages:
  - "apps/*"
  - "packages/*"


catalog:
  react: "^19.0.0"
  react-dom: "^19.0.0"
  typescript: "^5.7.2"
  "@types/react": "^19.0.8"
  "@types/react-dom": "^19.0.3"
  "tailwindcss": "^4.0.6"
  